server:
  port: 85
spring:
  application:
    name: prototypeconfig
  config:
    import: configserver:http://localhost:83
  profiles:
    active: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
